# Generated by Django 6.0.3 on 2026-03-26 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rodada_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='disponivel',
        ),
        migrations.AlterField(
            model_name='reserva',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='core.slot'),
        ),
    ]
