# Generated by Django 6.0.3 on 2026-03-27 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_slot_disponivel_alter_reserva_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='rodada',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.rodada'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rodada',
            name='nome',
            field=models.CharField(default='Rodada Principal', max_length=100),
        ),
        migrations.AddField(
            model_name='slot',
            name='rodada',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='core.rodada'),
            preserve_default=False,
        ),
    ]
