# Generated by Django 6.0.3 on 2026-03-27 17:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_reserva_rodada_rodada_nome_slot_rodada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rodada',
            name='empresa',
        ),
        migrations.AddField(
            model_name='rodada',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='rodada',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
