# Generated by Django 6.0.3 on 2026-03-27 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_rodada_empresa_rodada_data_alter_rodada_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='representante',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
