# Generated by Django 6.0.3 on 2026-03-29 23:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_expediente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Expediente',
        ),
        migrations.AlterUniqueTogether(
            name='reuniao',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='reuniao',
            name='empresa_a',
        ),
        migrations.RemoveField(
            model_name='reuniao',
            name='empresa_b',
        ),
        migrations.RemoveField(
            model_name='reuniao',
            name='slot',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='rodada',
        ),
        migrations.RemoveField(
            model_name='slothorario',
            name='evento',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='representante',
        ),
        migrations.RemoveField(
            model_name='rodada',
            name='data',
        ),
        migrations.AddField(
            model_name='evento',
            name='inicio',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='evento',
            name='termino',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='rodada',
            name='hora_fim',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='rodada',
            name='hora_inicio',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='mesa',
            name='rodada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesas', to='core.rodada'),
        ),
        migrations.DeleteModel(
            name='Reserva',
        ),
        migrations.DeleteModel(
            name='Reuniao',
        ),
        migrations.DeleteModel(
            name='Slot',
        ),
        migrations.DeleteModel(
            name='SlotHorario',
        ),
        migrations.AlterUniqueTogether(
            name='mesa',
            unique_together={('numero', 'rodada')},
        ),
    ]
