# Generated by Django 6.0.3 on 2026-03-30 00:18

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_mesa_delete_expediente_alter_reuniao_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='evento',
            name='inicio',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
        migrations.AlterField(
            model_name='evento',
            name='termino',
            field=models.TimeField(default=datetime.time(18, 0)),
        ),
    ]
