# Generated by Django 6.0.3 on 2026-03-30 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_evento_data_alter_evento_inicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rodada',
            name='evento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rodadas', to='core.evento'),
            preserve_default=False,
        ),
    ]
