# Generated by Django 6.0.3 on 2026-03-30 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='horario',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
