# Generated by Django 6.0.3 on 2026-03-30 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_reserva_horario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='inicio',
            new_name='inicio_ev',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='termino',
            new_name='termino_ev',
        ),
        migrations.RenameField(
            model_name='rodada',
            old_name='hora_fim',
            new_name='fim_ro',
        ),
        migrations.RenameField(
            model_name='rodada',
            old_name='hora_inicio',
            new_name='inicio_ro',
        ),
    ]
