# Generated by Django 6.0.3 on 2026-04-01 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_rename_inicio_evento_inicio_ev_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='site',
            field=models.CharField(blank=True),
        ),
    ]
