# Generated by Django 6.0.3 on 2026-04-01 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_empresa_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='site',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
