# Generated by Django 6.0.3 on 2026-04-03 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_empresa_site'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rodada',
            new_name='Reuniao',
        ),
    ]
