# Generated by Django 6.0.3 on 2026-04-03 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_rename_rodada_reuniao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mesa',
            old_name='rodada',
            new_name='reuniao',
        ),
        migrations.AlterUniqueTogether(
            name='mesa',
            unique_together={('numero', 'reuniao')},
        ),
    ]
