# Generated by Django 6.0.3 on 2026-04-03 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_rename_rodada_mesa_reuniao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='modalidade',
            field=models.CharField(blank=True, choices=[('COMPRADOR', 'Comprador'), ('EXPOSITOR', 'Expositor')], default='EXPOSITOR', max_length=255),
        ),
        migrations.AlterField(
            model_name='reuniao',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reunioes', to='core.evento'),
        ),
    ]
