# Generated by Django 6.0.3 on 2026-04-03 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_empresa_modalidade_alter_reuniao_evento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='descricao',
            new_name='interesses',
        ),
    ]
