# Generated by Django 6.0.3 on 2026-04-03 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_rename_descricao_empresa_interesses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interesse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='interesses',
        ),
        migrations.AddField(
            model_name='empresa',
            name='interesses',
            field=models.ManyToManyField(blank=True, related_name='empresas', to='core.interesse'),
        ),
    ]
