# Generated by Django 6.0.3 on 2026-04-06 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_interesse_remove_empresa_interesses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interesse',
            name='categoria',
            field=models.CharField(choices=[('PAIS', 'País'), ('PRECO', 'Faixa de Preço'), ('TIPO', 'Tipo de Produto'), ('PERFIL', 'Perfil Desejado'), ('REGIAO', 'Região do Brasil'), ('OUTRO', 'Outro')], default='OUTRO', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='interesse',
            unique_together={('categoria', 'nome')},
        ),
    ]
