# Generated by Django 6.0.3 on 2026-04-06 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_interesse_categoria_alter_interesse_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilComprador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rotulos_internacionais', models.IntegerField(blank=True, null=True)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
                ('paises_que_trabalha', models.ManyToManyField(blank=True, related_name='compradores_paises', to='core.interesse')),
                ('preco_medio', models.ManyToManyField(blank=True, related_name='compradores_preco', to='core.interesse')),
                ('regioes_interesse', models.ManyToManyField(blank=True, related_name='compradores_regioes', to='core.interesse')),
                ('tipos_produto', models.ManyToManyField(blank=True, related_name='compradores_tipos', to='core.interesse')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilExpositor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
                ('pais_origem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expositores_pais', to='core.interesse')),
                ('perfil_comprador_desejado', models.ManyToManyField(blank=True, related_name='expositores_perfil', to='core.interesse')),
                ('preco_faixa', models.ManyToManyField(blank=True, related_name='expositores_preco', to='core.interesse')),
                ('regioes_brasil', models.ManyToManyField(blank=True, related_name='expositores_regioes', to='core.interesse')),
                ('tipos_produto', models.ManyToManyField(blank=True, related_name='expositores_tipos', to='core.interesse')),
            ],
        ),
    ]
